-- Billy V2 upgrade migration

-- Add email to user_profiles
alter table if exists public.user_profiles
  add column if not exists email text;

create unique index if not exists idx_user_profiles_email
  on public.user_profiles (email)
  where email is not null;

-- Add include_birthdays to channel_settings
alter table if exists public.channel_settings
  add column if not exists include_birthdays boolean default true;

-- Create templates table for dynamic message templates
create table if not exists public.templates (
  id bigint generated by default as identity primary key,
  workspace_id text,
  type text not null check (type in ('birthday', 'anniversary')),
  message text not null,
  gif_urls text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists idx_templates_type_workspace
  on public.templates (type, workspace_id);
