create extension if not exists pgcrypto;

alter table if exists public.user_profiles
  add column if not exists workspace_id text,
  add column if not exists birth_year integer,
  add column if not exists anniv_year integer,
  add column if not exists birthday_opt_out boolean default false,
  add column if not exists anniversary_opt_out boolean default false,
  add column if not exists created_at timestamptz default now();

alter table if exists public.channel_settings
  add column if not exists workspace_id text,
  add column if not exists channel_name text,
  add column if not exists weekend_policy text default 'next_business_day',
  add column if not exists include_gif boolean default true,
  add column if not exists mention_channel boolean default false,
  add column if not exists tag_channel boolean default false,
  add column if not exists mention_settings text default 'celebrants_only',
  add column if not exists who_to_celebrate text default 'everyone',
  add column if not exists include_anniversaries boolean default true,
  add column if not exists language text default 'en',
  add column if not exists auto_collect boolean default false,
  add column if not exists frequency text default 'daily',
  add column if not exists style text default 'playful',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table if exists public.reminders
  add column if not exists workspace_id text,
  add column if not exists channel_id text,
  add column if not exists scope text default 'channel',
  add column if not exists who_to_notify text default 'channel',
  add column if not exists created_by text,
  add column if not exists updated_at timestamptz default now(),
  add column if not exists created_at timestamptz default now();

alter table if exists public.admins
  add column if not exists workspace_id text,
  add column if not exists channel_id text,
  add column if not exists created_at timestamptz default now();

alter table if exists public.employees
  add column if not exists workspace_id text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create table if not exists public.custom_messages (
  id bigint generated by default as identity primary key,
  slack_id text not null,
  workspace_id text,
  date date not null,
  type text not null default 'birthday' check (type in ('birthday', 'anniversary')),
  message text,
  gif_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table if exists public.custom_messages
  add column if not exists type text not null default 'birthday';

create table if not exists public.message_history (
  id bigint generated by default as identity primary key,
  slack_id text not null,
  workspace_id text,
  type text not null check (type in ('birthday', 'anniversary')),
  last_message_index integer,
  last_gif_index integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.sent_events (
  id uuid primary key default gen_random_uuid(),
  slack_id text not null,
  workspace_id text,
  type text not null check (type in ('birthday', 'anniversary')),
  date date not null,
  channel_id text not null,
  created_at timestamptz default now()
);

create index if not exists idx_employees_slack_id on public.employees (slack_id);
create index if not exists idx_user_profiles_slack_id on public.user_profiles (slack_id);
create index if not exists idx_channel_settings_channel_id on public.channel_settings (channel_id);
create index if not exists idx_reminders_channel_id on public.reminders (channel_id);
create index if not exists idx_admins_slack_id on public.admins (slack_id);
drop index if exists idx_custom_messages_event_key;
create unique index if not exists idx_custom_messages_event_key on public.custom_messages (slack_id, date, type);
create unique index if not exists idx_message_history_unique_key on public.message_history (slack_id, type);
create unique index if not exists idx_sent_events_unique_event on public.sent_events (slack_id, type, date, channel_id);
