-- Bulk templates migration
-- Stores multiple named templates per event type (birthday / anniversary)
-- Each template can have a message and multiple GIF URLs

create table if not exists public.bulk_templates (
  id          bigint generated by default as identity primary key,
  workspace_id text,
  type        text not null check (type in ('birthday', 'anniversary')),
  name        text not null default 'Template',
  message     text not null default '',
  intro_text  text not null default '',
  gif_urls    text[] default '{}',
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists idx_bulk_templates_type
  on public.bulk_templates (type);

-- Tracks which bulk template + gif index was last used per (slack_id, type)
-- so the scheduler can avoid repeating the same template consecutively.
create table if not exists public.bulk_template_history (
  id                    bigint generated by default as identity primary key,
  workspace_id          text,
  slack_id              text not null,
  type                  text not null check (type in ('birthday', 'anniversary')),
  last_template_id      bigint,
  last_gif_index        integer,
  updated_at            timestamptz default now(),
  created_at            timestamptz default now()
);

create unique index if not exists idx_bulk_template_history_unique
  on public.bulk_template_history (slack_id, type);
